// flow-typed signature: c9faa4940534ad3fbf048710fd3f9287
// flow-typed version: <<STUB>>/argv-split_v^2.0.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'argv-split'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'argv-split' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'argv-split/split' {
  declare module.exports: any;
}

declare module 'argv-split/test' {
  declare module.exports: any;
}

declare module 'argv-split/test/argv-split' {
  declare module.exports: any;
}

// Filename aliases
declare module 'argv-split/split.js' {
  declare module.exports: $Exports<'argv-split/split'>;
}
declare module 'argv-split/test.js' {
  declare module.exports: $Exports<'argv-split/test'>;
}
declare module 'argv-split/test/argv-split.js' {
  declare module.exports: $Exports<'argv-split/test/argv-split'>;
}
