// flow-typed signature: a87db0657ca35d1ef5fb4c5a37e935de
// flow-typed version: <<STUB>>/await-url_v^0.3.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'await-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'await-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'await-url/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'await-url/cli.js' {
  declare module.exports: $Exports<'await-url/cli'>;
}
declare module 'await-url/index' {
  declare module.exports: $Exports<'await-url'>;
}
declare module 'await-url/index.js' {
  declare module.exports: $Exports<'await-url'>;
}
