// flow-typed signature: e4deecce8c92d8a5f4dd936a9efeaa16
// flow-typed version: <<STUB>>/localtunnel_v^1.8.3/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'localtunnel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'localtunnel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'localtunnel/client' {
  declare module.exports: any;
}

declare module 'localtunnel/fail' {
  declare module.exports: any;
}

declare module 'localtunnel/lib/HeaderHostTransformer' {
  declare module.exports: any;
}

declare module 'localtunnel/lib/Tunnel' {
  declare module.exports: any;
}

declare module 'localtunnel/lib/TunnelCluster' {
  declare module.exports: any;
}

declare module 'localtunnel/request' {
  declare module.exports: any;
}

declare module 'localtunnel/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'localtunnel/client.js' {
  declare module.exports: $Exports<'localtunnel/client'>;
}
declare module 'localtunnel/fail.js' {
  declare module.exports: $Exports<'localtunnel/fail'>;
}
declare module 'localtunnel/lib/HeaderHostTransformer.js' {
  declare module.exports: $Exports<'localtunnel/lib/HeaderHostTransformer'>;
}
declare module 'localtunnel/lib/Tunnel.js' {
  declare module.exports: $Exports<'localtunnel/lib/Tunnel'>;
}
declare module 'localtunnel/lib/TunnelCluster.js' {
  declare module.exports: $Exports<'localtunnel/lib/TunnelCluster'>;
}
declare module 'localtunnel/request.js' {
  declare module.exports: $Exports<'localtunnel/request'>;
}
declare module 'localtunnel/test/index.js' {
  declare module.exports: $Exports<'localtunnel/test/index'>;
}
