// flow-typed signature: f363534529e5833348f2512d05efc997
// flow-typed version: <<STUB>>/now_v^8.3.11/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'now'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'now' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'now/download/dist/download' {
  declare module.exports: any;
}

declare module 'now/download/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'now/download/dist/download.js' {
  declare module.exports: $Exports<'now/download/dist/download'>;
}
declare module 'now/download/install.js' {
  declare module.exports: $Exports<'now/download/install'>;
}
