// flow-typed signature: dbc2576d107b9aab4482d7e48bb3f1e3
// flow-typed version: <<STUB>>/probot_v^3.0.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'probot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'probot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'probot/bin/probot-run' {
  declare module.exports: any;
}

declare module 'probot/bin/probot-simulate' {
  declare module.exports: any;
}

declare module 'probot/bin/probot' {
  declare module.exports: any;
}

declare module 'probot/lib/context' {
  declare module.exports: any;
}

declare module 'probot/lib/paginate' {
  declare module.exports: any;
}

declare module 'probot/lib/plugins/default' {
  declare module.exports: any;
}

declare module 'probot/lib/plugins/stats' {
  declare module.exports: any;
}

declare module 'probot/lib/private-key' {
  declare module.exports: any;
}

declare module 'probot/lib/resolver' {
  declare module.exports: any;
}

declare module 'probot/lib/robot' {
  declare module.exports: any;
}

declare module 'probot/lib/serializers' {
  declare module.exports: any;
}

declare module 'probot/lib/server' {
  declare module.exports: any;
}

declare module 'probot/lib/tunnel' {
  declare module.exports: any;
}

declare module 'probot/test/context' {
  declare module.exports: any;
}

declare module 'probot/test/fixtures/example' {
  declare module.exports: any;
}

declare module 'probot/test/fixtures/plugin/stub-plugin' {
  declare module.exports: any;
}

declare module 'probot/test/index' {
  declare module.exports: any;
}

declare module 'probot/test/plugins/default' {
  declare module.exports: any;
}

declare module 'probot/test/plugins/helper' {
  declare module.exports: any;
}

declare module 'probot/test/plugins/stats' {
  declare module.exports: any;
}

declare module 'probot/test/private-key' {
  declare module.exports: any;
}

declare module 'probot/test/resolver' {
  declare module.exports: any;
}

declare module 'probot/test/robot' {
  declare module.exports: any;
}

declare module 'probot/test/serializers' {
  declare module.exports: any;
}

declare module 'probot/test/server' {
  declare module.exports: any;
}

declare module 'probot/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'probot/bin/probot-run.js' {
  declare module.exports: $Exports<'probot/bin/probot-run'>;
}
declare module 'probot/bin/probot-simulate.js' {
  declare module.exports: $Exports<'probot/bin/probot-simulate'>;
}
declare module 'probot/bin/probot.js' {
  declare module.exports: $Exports<'probot/bin/probot'>;
}
declare module 'probot/index' {
  declare module.exports: $Exports<'probot'>;
}
declare module 'probot/index.js' {
  declare module.exports: $Exports<'probot'>;
}
declare module 'probot/lib/context.js' {
  declare module.exports: $Exports<'probot/lib/context'>;
}
declare module 'probot/lib/paginate.js' {
  declare module.exports: $Exports<'probot/lib/paginate'>;
}
declare module 'probot/lib/plugins/default.js' {
  declare module.exports: $Exports<'probot/lib/plugins/default'>;
}
declare module 'probot/lib/plugins/stats.js' {
  declare module.exports: $Exports<'probot/lib/plugins/stats'>;
}
declare module 'probot/lib/private-key.js' {
  declare module.exports: $Exports<'probot/lib/private-key'>;
}
declare module 'probot/lib/resolver.js' {
  declare module.exports: $Exports<'probot/lib/resolver'>;
}
declare module 'probot/lib/robot.js' {
  declare module.exports: $Exports<'probot/lib/robot'>;
}
declare module 'probot/lib/serializers.js' {
  declare module.exports: $Exports<'probot/lib/serializers'>;
}
declare module 'probot/lib/server.js' {
  declare module.exports: $Exports<'probot/lib/server'>;
}
declare module 'probot/lib/tunnel.js' {
  declare module.exports: $Exports<'probot/lib/tunnel'>;
}
declare module 'probot/test/context.js' {
  declare module.exports: $Exports<'probot/test/context'>;
}
declare module 'probot/test/fixtures/example.js' {
  declare module.exports: $Exports<'probot/test/fixtures/example'>;
}
declare module 'probot/test/fixtures/plugin/stub-plugin.js' {
  declare module.exports: $Exports<'probot/test/fixtures/plugin/stub-plugin'>;
}
declare module 'probot/test/index.js' {
  declare module.exports: $Exports<'probot/test/index'>;
}
declare module 'probot/test/plugins/default.js' {
  declare module.exports: $Exports<'probot/test/plugins/default'>;
}
declare module 'probot/test/plugins/helper.js' {
  declare module.exports: $Exports<'probot/test/plugins/helper'>;
}
declare module 'probot/test/plugins/stats.js' {
  declare module.exports: $Exports<'probot/test/plugins/stats'>;
}
declare module 'probot/test/private-key.js' {
  declare module.exports: $Exports<'probot/test/private-key'>;
}
declare module 'probot/test/resolver.js' {
  declare module.exports: $Exports<'probot/test/resolver'>;
}
declare module 'probot/test/robot.js' {
  declare module.exports: $Exports<'probot/test/robot'>;
}
declare module 'probot/test/serializers.js' {
  declare module.exports: $Exports<'probot/test/serializers'>;
}
declare module 'probot/test/server.js' {
  declare module.exports: $Exports<'probot/test/server'>;
}
declare module 'probot/test/setup.js' {
  declare module.exports: $Exports<'probot/test/setup'>;
}
